### ISSUE TITLE
Patterns

### ISSUE THREAD

**Issue by MimisK13** [yairEO/validator#31]
Is it possible for a pattern to be made specifically for letters and numbers, without accepting any other characters-symbol??

**Comment by SinuheM** [comment]
I was trying this
`<input type="text" pattern="letter">`

And add some lines in default settings (line 38)
`letter       : /^[A-Za-z ]+$/i,`

also near to the line 133

`case 'letter' :`
`regex = this.settings.regex.letter`
`break;`

**Comment by MimisK13** [comment]
Thank you very much!!!

**Comment by tiomno** [comment]
You shouldn't need to modify the source to make something like this work.

The documentation explains that the correct way to do this is to add the customised regular expression to the **pattern** attribute like this:

`<input type="text" pattern="^[A-Za-z ]+$">` 

I personally would like to have the option for adding new RegExp to the settings instead of filling the HTML with crafty regular expressions. ;)

I'll PR a change for this and hope @yairEO accepts it. :)

BTW, fantactic job @yairEO, thanks a lot!

**Comment by yairEO** [comment]
Thank you @tiomno :)
